#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow on
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
